### ISSUE TITLE
UnicodeDecodeError: incomplete multibyte sequence

### ISSUE THREAD

**Issue by fapdash** [JoshData/convert-outlook-msg-file#31]
I'm trying to convert a bunch of `msg` files via `python3 outlookmsgfile.py *.msg`.
Most files convert successfully, but a few fail, all with the same error.

I'm running this under WSL Ubuntu with Python 3.12.

Error message:

```
'cp950' codec can't decode byte 0xa1 in position 0: incomplete multibyte sequence
Traceback (most recent call last):
  File "/home/cynthia/git/convert-outlook-msg-file/venv/lib/python3.12/site-packages/rtfparse/parser.py", line 72, in parse_file
    self.parsed = entities.Group(encoding, file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cynthia/git/convert-outlook-msg-file/venv/lib/python3.12/site-packages/rtfparse/entities.py", line 181, in __init__
    self.structure.append(Group(self.encoding, file))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cynthia/git/convert-outlook-msg-file/venv/lib/python3.12/site-packages/rtfparse/entities.py", line 183, in __init__
    self.structure.append(Control_Symbol(self.encoding, file))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cynthia/git/convert-outlook-msg-file/venv/lib/python3.12/site-packages/rtfparse/entities.py", line 109, in __init__
    self.text = bytes((int(self.char, base=16),)).decode(self.encoding)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'cp950' codec can't decode byte 0xa1 in position 0: incomplete multibyte sequence
decoding with 'cp950' codec failed
```

**Comment by fapdash** [comment]
I tried to convert the files with [email-outlook-message-perl](https://github.com/mvz/email-outlook-message-perl) and it also had issues with these e-mails.
At this point I assume that those e-mails are actually somehow broken, closing.

**Comment by JoshData** [comment]
Thanks for investigating.
